- name: -------- create project  ---------
  file:
    path: "{{ansible_root}}/{{project_name}}/"
    state: directory
  tags: [create_project]


- name: ----------- create project yml ------------
  file:
    path: "{{ansible_root}}/{{project_name}}.yml"
    state: touch
  tags: [crate_prj_yml]

  
- name: ----------- create hosts  ------------
  file:
    path: "{{ansible_root}}/{{project_name}}/hosts"
    state: touch
  tags: [crate_prj_host]

- name: --------- create 7 directory ----------
  file: 
    path: "{{ansible_root}}/{{project_name}}/roles/{{project_name}}/{{item}}"
    state: directory
  loop:
    - tasks
    - vars
    - templates
    - handlers
    - files
    - defualts
    - meta
  tags: [seven_dir]

- name: ----------- create main.yml files ------------
  file:
    path: "{{ansible_root}}/{{project_name}}/roles/{{project_name}}/{{item}}/main.yml"
    state: touch
  loop:
    - tasks
    - vars
    - defualts
    - handlers
    - meta
  tags: [create_main_yml]
